WITH RECURSIVE GEN AS ( /* WITH = 쿼리 안에서만 살아있는 임시테이블 정의
                            RECURSIVE = 새행이 나오지 않을 때까지 돌림 LIKE 반복문
                         */
    SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT e.ID, g.GENERATION + 1
    FROM ECOLI_DATA e
    JOIN GEN g ON e.PARENT_ID = g.ID
)
SELECT COUNT(*) AS COUNT, GENERATION
FROM GEN
WHERE ID NOT IN (
    SELECT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION;