-- 코드를 작성해주세요
SELECT c.ITEM_ID, c.ITEM_NAME, c.RARITY
FROM ITEM_INFO t
JOIN ITEM_TREE p ON t.ITEM_ID = p.PARENT_ITEM_ID
JOIN ITEM_INFO c ON p.ITEM_ID = c.ITEM_ID
WHERE t.RARITY = 'RARE'
ORDER BY c.ITEM_ID DESC;